### ISSUE TITLE
button + pill + small doesn't align with magic numbers

### ISSUE THREAD

**Issue by pearofducks** [fabric-ds/css#8]
36px -> 32px

**Comment by Skadefryd** [comment]
This thing does align, Its just to small to fit a 24px icon like the example in the doc uses. Its currently setup using min-height, min-width: 32px   with paddings. (Paddings are there to handle text-issues), I guess we could tune paddings to work with specific versions of icons instead if that was the intended use(?), but could also just override the class manually. Due to the fact that these are combinations and sizes that are not supposed to be used anywhere, I say we ignore them for now?

**Comment by pearofducks** [comment]
Ignore for now sounds like a good solution! 💯
